# Build ePub (pdf is currently failing)
formats:
  - epub

# Conda requirements file
# conda:
#   file: docs/environment.yml

# pip requirements file for building sphinx docs (e.g. nbsphinx)
requirements_file: requirements-dev.txt

# Use python 3 for building
python:
  version: 3.5
