language: python
sudo: false

cache:
  directories:
    - $HOME/.theano
    - $HOME/minicoda2
    - $HOME/minicoda3

addons:
  apt_packages:
    - pandoc

before_install:
  - . ./scripts/install_miniconda.sh
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=":99.0"

install:
  - . ./scripts/create_testenv.sh
  - pip install coveralls pylint 
  - pip install travis-sphinx==2.0.0
  - pip install -r requirements-dev.txt

env:
    - PYTHON_VERSION=2.7 FLOATX='float32' TESTCMD="--durations=10 --cov-append pymc3/tests/test_variational_inference.py::test_sample_aevb"

script:
  - . ./scripts/test.sh $TESTCMD
  - . ./scripts/confirm_mpl_optional.sh

after_success:
  - echo "success!" && sleep 20 && cat /tmp/theano_compilation_error_* && sleep 20;
  - if [[ "$BUILD_DOCS" == "true" ]]; then travis-sphinx deploy -c "docs.pymc.io"; fi
  - coveralls

after_failure:
  - echo "failure!" && sleep 20 && cat /tmp/theano_compilation_error_* && sleep 20;
