language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - . ./scripts/install_miniconda.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - if [ ${MATPLOTLIB} = "1.2" ]; then mkdir $HOME/.matplotlib; fi
  - if [ ${MATPLOTLIB} = "1.2" ]; then cp ${SRCDIR}/tools/matplotlibrc $HOME/.matplotlib/matplotlibrc; fi
  #- mkdir -p $HOME/.config/matplotlib; echo "backend: agg" > $HOME/.config/matplotlib/matplotlibrc

install:
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes jupyter pyzmq numpy scipy nose matplotlib pandas Cython patsy statsmodels joblib
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then conda install --yes mock enum34; fi
  - pip install --no-deps numdifftools
  - pip install git+https://github.com/Theano/Theano.git
  - pip install git+https://github.com/mahmoudimus/nose-timer.git
  - python setup.py build_ext --inplace

env:
  - TESTCMD=" -vv --with-timer -e test_examples -e test_distributions" PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
  - TESTCMD=" -vv --with-timer pymc3.tests.test_distributions" PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
  - TESTCMD=" -vv --with-timer pymc3.tests.test_distributions_random" PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
script:
  - THEANO_FLAGS='gcc.cxxflags="-march=core2"' nosetests $TESTCMD

after_success:
  - bash <(curl -s https://codecov.io/bash)
