name: pymc3-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz>=0.9
  - theano-pymc==1.0.11
  - numpy>=1.13
  - scipy>=0.18
  - pandas >=0.18
  - patsy>=0.5
  - fastprogress>=0.2
  - h5py>=2.7
  - typing-extensions>=3.7
  - python-graphviz
  - ipython>=7.16
  - pytest-cov>=2.5
  - pytest>=3.0
  - watermark
  - mkl-service
  - dill
  - libblas=*=*mkl
