name: pymc3-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - theano-pymc==1.0.11
  - patsy>=0.5
  - h5py>=2.7
  - python-graphviz
  - ipython>=7.16
  - pytest-cov>=2.5
  - pytest>=3.0
  - watermark
  - mkl-service
  - libblas=*=*mkl
