name: pymc3-dev-py39
channels:
- conda-forge
- defaults
dependencies:
- h5py>=2.7
- ipython>=7.16
- libblas=*=*mkl
- mkl-service
- nbsphinx>=0.4
- numpy>=1.15,<1.22.2
- numpydoc<1.2
- pip
- pre-commit>=2.8.0
- pytest-cov>=2.5
- pytest>=3.0
- python-graphviz
- python=3.9
- recommonmark>=0.4
- scipy>=1.4.1
- sphinx-autobuild>=0.7
- sphinx>=1.5
- watermark
- pip:
  - deprecat
