name: pymc3-dev-py36
channels:
- conda-forge
- defaults
dependencies:
- arviz>=0.9
- contextvars
- dataclasses
- dill
- fastprogress>=0.2
- h5py>=2.7
- ipython>=7.16
- libblas=*=*mkl
- mkl-service
- nbsphinx>=0.4
- numpy>=1.13
- numpydoc>=0.9
- pandas>=0.18
- patsy>=0.5
- pre-commit>=2.8.0
- pytest-cov>=2.5
- pytest>=3.0
- python-graphviz
- python=3.6
- recommonmark>=0.4
- scipy>=0.18
- sphinx-autobuild>=0.7
- sphinx>=1.5
- theano-pymc=1.0.12
- typing-extensions>=3.7
- watermark
