name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"  # Run pre-commit on oldest supported Python version
    - uses: pre-commit/action@v3.0.1
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-envs/environment-test.yml
          create-args: >-
            python=3.10
          environment-name: pymc-test
          init-shell: bash
          cache-environment: true
      - name: Install-pymc and mypy dependencies
        run: |
          pip install -e .
          pip install --pre -U polyagamma
          python --version
      - name: Run mypy
        run: |
          python ./scripts/run_mypy.py --verbose
