name: release-pipeline

#on:
#  release:
#    types:
#      - created
# !!!!!!!!!!!! TODO: uncomment the block above & remove the next line !!!!!!!!!!!!
on: [push, pull_request]

jobs:
  release-job:
    runs-on: ubuntu-latest
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    # TODO: ideally, this pipeline should run parallelized tests in upstream jobs..
    #- name: Install test tooling
    #  run: |
    #    pip install pytest pytest-cov nose nose-parameterized
    #    pip install -r requirements.txt
    #- name: Run tests
    #  run: |
    #    pytest --cov=./pymc3 --cov-report term-missing pymc3/
    - name: Install release tooling
      run: |
        pip install twine wheel
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: Check version number match
      run: |
# TODO: take out the next line, which simulates the tag
        export GITHUB_REF="refs/tags/v3.9.0"
        echo "GITHUB_REF: ${GITHUB_REF}"
        # The GITHUB_REF should be something like "refs/tags/v3.x.x"
        # Make sure the package version is the same as the tag
        grep -Rq "^Version: ${GITHUB_REF:11}$" pymc3.egg-info/PKG-INFO
    - name: Publish to PyPI
      run: |
        twine check dist/*
# TODO: twine upload --repository pypi --username __token__ --password ${PYPI_TOKEN} dist/*
  test-install-job:
    needs: release-job
    runs-on: ubuntu-latest
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Give PyPI a chance to update the index
      run: sleep 120
    - name: Install from PyPI
      run: |
        pip install pymc3
# TODO: pip install pymc3==${GITHUB_REF:11}
